import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid min-h-screen grid-rows-[auto_1fr_auto]">
        <header className="px-3 py-4">
        <a href="/" className="text-2xl font-semibold text-center">Dave Hill</a>
        </header>
        <main>{children}</main>
        <footer className="px-3 py-4 flex justify-center">
          <p>Copyright &copy; {new Date().getFullYear()} Dave Hill.</p>
        </footer>
      </body>
    </html>
  );
}
